# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gRPC import virtualmirror_v2_pb2 as virtualmirror__v2__pb2


class MirrorStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SkeletonFrame = channel.unary_unary(
                '/virtualmirror_v2.Mirror/SkeletonFrame',
                request_serializer=virtualmirror__v2__pb2.Frame.SerializeToString,
                response_deserializer=virtualmirror__v2__pb2.Result.FromString,
                )
        self.PoseDetected = channel.unary_unary(
                '/virtualmirror_v2.Mirror/PoseDetected',
                request_serializer=virtualmirror__v2__pb2.Pose.SerializeToString,
                response_deserializer=virtualmirror__v2__pb2.Result.FromString,
                )
        self.ActionDetected = channel.unary_unary(
                '/virtualmirror_v2.Mirror/ActionDetected',
                request_serializer=virtualmirror__v2__pb2.Action.SerializeToString,
                response_deserializer=virtualmirror__v2__pb2.Result.FromString,
                )


class MirrorServicer(object):
    """Interface exported by the server.
    """

    def SkeletonFrame(self, request, context):
        """輸出骨架偵測畫面
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PoseDetected(self, request, context):
        """輸出姿態事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActionDetected(self, request, context):
        """輸出動作事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MirrorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SkeletonFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SkeletonFrame,
                    request_deserializer=virtualmirror__v2__pb2.Frame.FromString,
                    response_serializer=virtualmirror__v2__pb2.Result.SerializeToString,
            ),
            'PoseDetected': grpc.unary_unary_rpc_method_handler(
                    servicer.PoseDetected,
                    request_deserializer=virtualmirror__v2__pb2.Pose.FromString,
                    response_serializer=virtualmirror__v2__pb2.Result.SerializeToString,
            ),
            'ActionDetected': grpc.unary_unary_rpc_method_handler(
                    servicer.ActionDetected,
                    request_deserializer=virtualmirror__v2__pb2.Action.FromString,
                    response_serializer=virtualmirror__v2__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'virtualmirror_v2.Mirror', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mirror(object):
    """Interface exported by the server.
    """

    @staticmethod
    def SkeletonFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/virtualmirror_v2.Mirror/SkeletonFrame',
            virtualmirror__v2__pb2.Frame.SerializeToString,
            virtualmirror__v2__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PoseDetected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/virtualmirror_v2.Mirror/PoseDetected',
            virtualmirror__v2__pb2.Pose.SerializeToString,
            virtualmirror__v2__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ActionDetected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/virtualmirror_v2.Mirror/ActionDetected',
            virtualmirror__v2__pb2.Action.SerializeToString,
            virtualmirror__v2__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
