# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: virtualmirror_v2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16virtualmirror_v2.proto\x12\x10virtualmirror_v2\"\xa8\x01\n\x05\x46rame\x12\x0e\n\x06\x63\x61mera\x18\x01 \x01(\x05\x12\x13\n\x0b\x66rame_index\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x15\n\rskeleton_type\x18\x04 \x01(\t\x12\x11\n\tskeletons\x18\x05 \x01(\t\x12\x16\n\x0epose_estimated\x18\x06 \x01(\t\x12\x11\n\tframe_raw\x18\x07 \x01(\t\x12\x12\n\nframe_mask\x18\x08 \x01(\t\"L\n\x04Pose\x12\x0e\n\x06\x63\x61mera\x18\x01 \x01(\x05\x12\x13\n\x0b\x66rame_index\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x0c\n\x04pose\x18\x04 \x01(\t\"P\n\x06\x41\x63tion\x12\x0e\n\x06\x63\x61mera\x18\x01 \x01(\x05\x12\x13\n\x0b\x66rame_index\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\"-\n\x06Result\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x15\n\rerror_message\x18\x02 \x01(\t2\xda\x01\n\x06Mirror\x12\x44\n\rSkeletonFrame\x12\x17.virtualmirror_v2.Frame\x1a\x18.virtualmirror_v2.Result\"\x00\x12\x42\n\x0cPoseDetected\x12\x16.virtualmirror_v2.Pose\x1a\x18.virtualmirror_v2.Result\"\x00\x12\x46\n\x0e\x41\x63tionDetected\x12\x18.virtualmirror_v2.Action\x1a\x18.virtualmirror_v2.Result\"\x00\x42:\n\x1cio.grpc.5gaiot.virtualmirrorB\x12VirtualMirrorProtoP\x01\xa2\x02\x03\x35VMb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'virtualmirror_v2_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034io.grpc.5gaiot.virtualmirrorB\022VirtualMirrorProtoP\001\242\002\0035VM'
  _globals['_FRAME']._serialized_start=45
  _globals['_FRAME']._serialized_end=213
  _globals['_POSE']._serialized_start=215
  _globals['_POSE']._serialized_end=291
  _globals['_ACTION']._serialized_start=293
  _globals['_ACTION']._serialized_end=373
  _globals['_RESULT']._serialized_start=375
  _globals['_RESULT']._serialized_end=420
  _globals['_MIRROR']._serialized_start=423
  _globals['_MIRROR']._serialized_end=641
# @@protoc_insertion_point(module_scope)
